log_level: debug


plank:
  job_url_template: 'https://tekton-releases.appspot.com/build/tekton-prow/{{if or (eq .Spec.Type "presubmit") (eq .Spec.Type "batch")}}pr-logs/pull{{with .Spec.Refs}}/{{.Org}}_{{.Repo}}{{end}}{{else}}logs{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
  report_template: '[Full PR test history](https://tekton-releases.appspot.com/pr/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](https://prow.tekton.dev/pr/{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).'
  pod_pending_timeout: 60m

tide:
  queries:
  - repos:
    - bobcatfish/catservice
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge/hold
    - do-not-merge/work-in-progress
  merge_method:
    bobcatfish/catservice: rebase
  target_url: http://35.244.148.160/tide

presubmits:
  bobcatfish/catservice:
  - name: do-the-pipeline
    agent: tekton-pipeline
    rerun_command: "/run do-the-pipeline"
    trigger: "(?m)^/run do-the-pipeline,?(\\s+|$)"
    always_run: true
    skip_report: false
    pipeline_run_spec:
      trigger:
        type: manual
      pipelineRef:
        name: special-pipeline
      resources:
      - name: git
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF

periodics:
- cron: "* * * * *"
  name: make-release
  agent: tekton-pipeline
  extra_refs:
  - org: bobcatfish
    repo: catservice
    base_ref: nightly
  pipeline_run_spec:
    trigger:
      type: manual
    pipelineRef:
      name: pipeline-release
    params:
    - name: package
      value: github.com/bobcatfish/catservice
    - name: imageRegistry
      value: gcr.io/christiewilson-catfactory
    resources:
    - name: bucket
      resourceRef:
        name: catservice-bucket
    - name: catservice-image
      resourceRef:
        name: catservice-image
    - name: catservice
      resourceRef:
        name: PROW_EXTRA_GIT_REF_0

