apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pr-pipeline
  namespace: getting-started
spec:
  params:
  - name: report-to-github
    default: "no"
  resources:
  - name: source-repo
    type: git
  - name: pr
    type: pullRequest
  tasks:
  - name: setstatus-inprogress
    taskRef:
      name: set-status
    resources:
      inputs:
      - name: pr
        resource: pr
      outputs:
      - name: pr
        resource: pr
    params:
    - name: report-to-github
      value: $(params.report-to-github)
    - name: status
      value: "in_progress"
  - name: unit-test
    runAfter: [setstatus-inprogress]
    taskRef:
      name: golang-test-pr
    params:
    - name: report-to-github
      value: $(params.report-to-github)
    - name: package
      value: github.com/bobcatfish/catservice
    resources:
      inputs:
      - name: source
        resource: source-repo
      - name: pr
        resource: pr
      outputs:
      - name: pr
        resource: pr