apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: publish-tekton-pipelines
spec:
  inputs:
    resources:
    - name: source
      type: git
      targetPath: go/src/github.com/bobcatfish/catservice
    - name: bucket
      type: storage
    params:
    - name: imageRegistry
      description: TODO(#569) This is a hack to make it easy for folks to switch the registry being used by the many many image outputs
    - name: pathToProject
      description: The path to the folder in the go/src dir that contains the project, which is used by `ko` to name the resulting images
  outputs:
    resources:
    - name: bucket
      type: storage
    - name: builtCatService
  steps:

  - name: ensure-release-dirs-exist
    image: busybox
    command: ["mkdir"]
    args:
    - "-p"
    - "/workspace/bucket/latest/"
    - "/workspace/bucket/previous/"

  - name: run-ko
    # TODO(#639) we should be able to use the image built by an upstream Task here instead of hardcoding
    image: gcr.io/tekton-releases/ko-ci
    env:
    - name: KO_DOCKER_REPO
      value: $(inputs.params.imageRegistry)
    - name: GOPATH
      value: /workspace/go
    - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
      value: /secret/release.json
    command:
    - /bin/sh
    args:
    - -ce
    - |
      set -e
      set -x

      # Auth with CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
      gcloud auth configure-docker

      # ko requires this variable to be set in order to set image creation timestamps correctly https://github.com/google/go-containerregistry/pull/146
      export SOURCE_DATE_EPOCH=`date +%s`

      # Publish images and create release.yaml
      ko resolve --preserve-import-paths > /workspace/bucket/latest/release.yaml
    volumeMounts:
      - name: gcp-secret
        mountPath: /secret

  - name: copy-to-tagged-bucket
    image: busybox
    workingDir: "/workspace/bucket"
    command:
    - /bin/sh
    args:
    - -ce
    - |
      # TODO: "nightly" flag for versionTag?
      # Nightly releases should use vYYYYMMDD-commit
      COMMIT=$(git rev-parse HEAD | cut -c 1-10)
      #DATE=$(date +"%Y%m%d")
      DATE=$(date +"%Y%m%d-%H%M%S")
      VERSION_TAG="$DATE-$COMMIT"

      mkdir -p /workspace/bucket/previous/$VERSION_TAG/
      cp /workspace/bucket/latest/release.yaml /workspace/bucket/previous/$VERSION_TAG/release.yaml

  - name: tag-images
    image: google/cloud-sdk
    command:
    - /bin/bash
    args:
    - -ce
    - |
      set -e
      set -x

      REGIONS=(us eu asia)
      IMAGES=(
        $(inputs.params.imageRegistry)/$(inputs.params.pathToProject)/$(outputs.resources.builtCatService.url)
      )
      # Parse the built images from the release.yaml generated by ko
      BUILT_IMAGES=( $(/workspace/go/src/github.com/bobcatfish/catservice/tekton/koparse.py --path /workspace/bucket/latest/release.yaml --base $(inputs.params.imageRegistry)/$(inputs.params.pathToProject) --images ${IMAGES[@]}) )

      # Tag the images and put them in all the regions
      for IMAGE in "${BUILT_IMAGES[@]}"
      do
        IMAGE_WITHOUT_SHA=${IMAGE%%@*}
        gcloud -q container images add-tag ${IMAGE} ${IMAGE_WITHOUT_SHA}:latest
        gcloud -q container images add-tag ${IMAGE} ${IMAGE_WITHOUT_SHA}:VERSION_TAG
        for REGION in "${REGIONS[@]}"
        do
          for TAG in "latest" $VERSION_TAG
          do
            gcloud -q container images add-tag ${IMAGE} ${REGION}.${IMAGE_WITHOUT_SHA}:$TAG
          done
        done
      done
