---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: run-pipeline-release-
spec:
  pipelineRef:
    name: pipeline-release
  trigger:
    type: manual
  params:
  - name: package
    value: github.com/bobcatfish/catservice
  - name: imageRegistry
    value: gcr.io/christiewilson-catfactory
  resources:
  - name: catservice
    resourceRef:
      name: catservice
  - name: bucket
    resourceRef:
      name: catservice-bucket
  - name: catservice-image
    resourceRef:
      name: catservice-image
