---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-release
spec:
  params:
  - name: package
    description: package to release
  - name: imageRegistry
  resources:
  - name: catservice
    type: git
  - name: bucket
    type: storage
  - name: catservice-image
    type: image
  tasks:
    - name: lint
      taskRef:
        name: golangci-lint
      params:
        - name: package
          value: ${params.package}
        - name: flags
          value: -v
      resources:
        inputs:
          - name: source
            resource: catservice
    - name: unit-tests
      runAfter: [lint]
      taskRef:
        name: golang-test
      params:
        - name: package
          value: ${params.package}
      resources:
        inputs:
          - name: source
            resource: catservice
