apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: catservice
spec:
  type: git
  params:
  - name: url
    value: https://github.com/bobcatfish/catservice
  - name: revision
    value: nightly
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: catservice-bucket
spec:
  type: storage
  params:
   - name: type
     value: gcs
   - name: location
     value: gs://catservice-releases
   - name: dir
     value: "y"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: catservice-image
spec:
  type: image
  params:
   - name: url
     value: catservice
