apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: set-status
  namespace: getting-started
spec:
  inputs:
    resources:
    - name: pr
      type: pullRequest
    params:
    - name: status
      type: string
    - name: report-to-github
  outputs:
    resources:
    - name: pr
      type: pullRequest
  steps:
  - name: set
    image: ubuntu
    command: ['bash']
    args:
    - -c
    - |
        set -ex
        if [[ $(inputs.params.report-to-github) -eq "yes" ]]; then
          cp -r /workspace/pr/ /workspace/output/
          ls -laR /workspace/output/pr
          cat <<EOF > /workspace/output/pr/status/tekton.json
          {
            "ID": "tekton",
            "Code": "$(inputs.params.status)",
            "Description": "Tekton is running"
          }
        EOF
        fi
